version: '2'
services:
  hastebin:
    build: hastebin/
    image: registry.example.com/demo/${STACKNAME}-hastebin:${VERSION}
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: host_type=common,region=demo
      io.rancher.scheduler.affinity:container_label_soft: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.pull_image: always
      loadbalancer.https: true
    links:
      - redis:redis
  redis:
    build: redis/
    image: registry.example.com/demo/${STACKNAME}-redis:${VERSION}
    stdin_open: true
    tty: true
    volumes:
    - ${PERSISTENT_VOLUME}:/data
    labels:
      io.rancher.scheduler.affinity:host_label: host_type=common,region=demo
      io.rancher.container.pull_image: always
